// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrayerTimeTracker.Api.Data;

#nullable disable

namespace PrayerTimeTracker.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250721210905_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrayerTimeTracker.Api.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Country")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "UAE",
                            Name = "Dubai"
                        },
                        new
                        {
                            Id = 2,
                            Country = "UAE",
                            Name = "Abu Dhabi"
                        },
                        new
                        {
                            Id = 3,
                            Country = "UAE",
                            Name = "Sharjah"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Saudi Arabia",
                            Name = "Riyadh"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Saudi Arabia",
                            Name = "Makkah"
                        });
                });

            modelBuilder.Entity("PrayerTimeTracker.Api.Models.Mosque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Mosques");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Jumeirah Beach Road, Dubai",
                            CityId = 1,
                            Name = "Jumeirah Mosque"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bur Dubai, Dubai",
                            CityId = 1,
                            Name = "Dubai Grand Mosque"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Sheikh Rashid Bin Saeed Street, Abu Dhabi",
                            CityId = 2,
                            Name = "Sheikh Zayed Grand Mosque"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Buhaira Corniche, Sharjah",
                            CityId = 3,
                            Name = "Al Noor Mosque"
                        },
                        new
                        {
                            Id = 5,
                            Address = "King Fahd Road, Riyadh",
                            CityId = 4,
                            Name = "King Fahd Mosque"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Makkah al Mukarramah, Makkah",
                            CityId = 5,
                            Name = "Masjid al-Haram"
                        });
                });

            modelBuilder.Entity("PrayerTimeTracker.Api.Models.PrayerTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("Asr")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Dhuhr")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Fajr")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Isha")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Maghrib")
                        .HasColumnType("time without time zone");

                    b.Property<int>("MosqueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MosqueId");

                    b.ToTable("PrayerTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Asr = new TimeOnly(15, 45, 0),
                            Date = new DateOnly(2025, 7, 22),
                            Dhuhr = new TimeOnly(12, 15, 0),
                            Fajr = new TimeOnly(5, 15, 0),
                            Isha = new TimeOnly(20, 0, 0),
                            Maghrib = new TimeOnly(18, 30, 0),
                            MosqueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Asr = new TimeOnly(15, 40, 0),
                            Date = new DateOnly(2025, 7, 22),
                            Dhuhr = new TimeOnly(12, 10, 0),
                            Fajr = new TimeOnly(5, 10, 0),
                            Isha = new TimeOnly(19, 55, 0),
                            Maghrib = new TimeOnly(18, 25, 0),
                            MosqueId = 2
                        },
                        new
                        {
                            Id = 3,
                            Asr = new TimeOnly(15, 50, 0),
                            Date = new DateOnly(2025, 7, 22),
                            Dhuhr = new TimeOnly(12, 20, 0),
                            Fajr = new TimeOnly(5, 20, 0),
                            Isha = new TimeOnly(20, 5, 0),
                            Maghrib = new TimeOnly(18, 35, 0),
                            MosqueId = 3
                        },
                        new
                        {
                            Id = 4,
                            Asr = new TimeOnly(15, 42, 0),
                            Date = new DateOnly(2025, 7, 22),
                            Dhuhr = new TimeOnly(12, 12, 0),
                            Fajr = new TimeOnly(5, 12, 0),
                            Isha = new TimeOnly(19, 57, 0),
                            Maghrib = new TimeOnly(18, 27, 0),
                            MosqueId = 4
                        },
                        new
                        {
                            Id = 5,
                            Asr = new TimeOnly(15, 15, 0),
                            Date = new DateOnly(2025, 7, 22),
                            Dhuhr = new TimeOnly(11, 45, 0),
                            Fajr = new TimeOnly(4, 45, 0),
                            Isha = new TimeOnly(19, 30, 0),
                            Maghrib = new TimeOnly(18, 0, 0),
                            MosqueId = 5
                        },
                        new
                        {
                            Id = 6,
                            Asr = new TimeOnly(15, 20, 0),
                            Date = new DateOnly(2025, 7, 22),
                            Dhuhr = new TimeOnly(11, 50, 0),
                            Fajr = new TimeOnly(4, 50, 0),
                            Isha = new TimeOnly(19, 35, 0),
                            Maghrib = new TimeOnly(18, 5, 0),
                            MosqueId = 6
                        },
                        new
                        {
                            Id = 7,
                            Asr = new TimeOnly(15, 46, 0),
                            Date = new DateOnly(2025, 7, 23),
                            Dhuhr = new TimeOnly(12, 16, 0),
                            Fajr = new TimeOnly(5, 16, 0),
                            Isha = new TimeOnly(20, 1, 0),
                            Maghrib = new TimeOnly(18, 31, 0),
                            MosqueId = 1
                        },
                        new
                        {
                            Id = 8,
                            Asr = new TimeOnly(15, 41, 0),
                            Date = new DateOnly(2025, 7, 23),
                            Dhuhr = new TimeOnly(12, 11, 0),
                            Fajr = new TimeOnly(5, 11, 0),
                            Isha = new TimeOnly(19, 56, 0),
                            Maghrib = new TimeOnly(18, 26, 0),
                            MosqueId = 2
                        },
                        new
                        {
                            Id = 9,
                            Asr = new TimeOnly(15, 51, 0),
                            Date = new DateOnly(2025, 7, 23),
                            Dhuhr = new TimeOnly(12, 21, 0),
                            Fajr = new TimeOnly(5, 21, 0),
                            Isha = new TimeOnly(20, 6, 0),
                            Maghrib = new TimeOnly(18, 36, 0),
                            MosqueId = 3
                        });
                });

            modelBuilder.Entity("PrayerTimeTracker.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@prayertracker.com",
                            PasswordHash = "$2a$11$I2ZthOrBdWs8lbmDeM486O4mOhI47LPZQVGudh9GDV1IVPPq2SXFW",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "test@prayertracker.com",
                            PasswordHash = "$2a$11$zcXV0MufoYQB6pnl3H0pZ.TVydZhEw/vHml19WsG8GZaPxUIC8oeu",
                            Role = "User",
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("PrayerTimeTracker.Api.Models.Mosque", b =>
                {
                    b.HasOne("PrayerTimeTracker.Api.Models.City", "City")
                        .WithMany("Mosques")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("PrayerTimeTracker.Api.Models.PrayerTime", b =>
                {
                    b.HasOne("PrayerTimeTracker.Api.Models.Mosque", "Mosque")
                        .WithMany("PrayerTimes")
                        .HasForeignKey("MosqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mosque");
                });

            modelBuilder.Entity("PrayerTimeTracker.Api.Models.City", b =>
                {
                    b.Navigation("Mosques");
                });

            modelBuilder.Entity("PrayerTimeTracker.Api.Models.Mosque", b =>
                {
                    b.Navigation("PrayerTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
